# Generated by Django 3.0.10 on 2025-01-05 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=126, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('director_name', models.CharField(max_length=126, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='renderer.Poster')),
            ],
        ),
    ]
